In [86]:
#pip install numpy
import numpy as np

In [4]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
np.zeros([1])


array([0.])

In [7]:
np.zeros((1))

array([0.])

In [8]:
np.zeros((5,2,8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [10]:
np.ones([1,3,1])

array([[[1.],
        [1.],
        [1.]]])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
np.arange(4,20) # va en este intervalo [4,20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(-2)

array([], dtype=int32)

In [16]:
np.arange(-12,1)

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [21]:
arreglo_pares=np.arange(0,20,2)

In [22]:
print(arreglo_pares.size)
print(len(arreglo_pares))
arreglo_tres_dimensiones = np.zeros((2,3,4))
print(arreglo_tres_dimensiones.shape)

10
10
(2, 3, 4)


In [24]:
arreglo_pares.reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [25]:
arreglo_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [27]:
arreglo = np.arange(24)
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [29]:
a= np.array([10,10,10])
b= np.array([5,5,5])

In [30]:
#suma
a+b

array([15, 15, 15])

In [31]:
#resta
a-b

array([5, 5, 5])

In [32]:
#multiplicacion
a*b

array([50, 50, 50])

In [33]:
#división
a/b

array([2., 2., 2.])

In [44]:
c=np.arange(1,13).reshape(2,3,2)

In [45]:
d = np.arange(12,24).reshape(2,3,2)
d

array([[[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [46]:
d+c

array([[[13, 15],
        [17, 19],
        [21, 23]],

       [[25, 27],
        [29, 31],
        [33, 35]]])

In [47]:
d-c

array([[[11, 11],
        [11, 11],
        [11, 11]],

       [[11, 11],
        [11, 11],
        [11, 11]]])

In [48]:
d*c

array([[[ 12,  26],
        [ 42,  60],
        [ 80, 102]],

       [[126, 152],
        [180, 210],
        [242, 276]]])

In [49]:
d/c

array([[[12.        ,  6.5       ],
        [ 4.66666667,  3.75      ],
        [ 3.2       ,  2.83333333]],

       [[ 2.57142857,  2.375     ],
        [ 2.22222222,  2.1       ],
        [ 2.        ,  1.91666667]]])

In [50]:
#Mod
d%c

array([[[ 0,  1],
        [ 2,  3],
        [ 1,  5]],

       [[ 4,  3],
        [ 2,  1],
        [ 0, 11]]], dtype=int32)

In [51]:
#Mod
d*10

array([[[120, 130],
        [140, 150],
        [160, 170]],

       [[180, 190],
        [200, 210],
        [220, 230]]])

In [52]:
d=d/15


In [53]:
d


array([[[0.8       , 0.86666667],
        [0.93333333, 1.        ],
        [1.06666667, 1.13333333]],

       [[1.2       , 1.26666667],
        [1.33333333, 1.4       ],
        [1.46666667, 1.53333333]]])

In [54]:
d=d*5
d

array([[[4.        , 4.33333333],
        [4.66666667, 5.        ],
        [5.33333333, 5.66666667]],

       [[6.        , 6.33333333],
        [6.66666667, 7.        ],
        [7.33333333, 7.66666667]]])

In [55]:
arreglo_muestra = np.arange(20).reshape(5,2,2)
arreglo_muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [56]:
resp = arreglo_muestra >5

In [57]:
resp

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [58]:
arreglo_muestra[resp]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [75]:
resp_dos = arreglo_muestra >6
res =arreglo_muestra[resp_dos] <14
re = arreglo_muestra[resp_dos][res]%2 == 0

arreglo_muestra[resp_dos][res][re]


array([ 8, 10, 12])

In [88]:
arrelo_doce = np.arange(12)
arrelo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [89]:
arrelo_doce.sum()

66

In [90]:
arrelo_doce.min()

0

In [91]:
arrelo_doce.max()

11

In [93]:
arrelo_doce.reshape(3,2,2).sum(axis=0)

array([[12, 15],
       [18, 21]])

In [94]:
arrelo_doce.reshape(3,2,2).sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [95]:
arrelo_doce.reshape(3,2,2).sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])